huskyとlint-staged追加,GitHubActionsの設定ファイル追加
phihash/QuizReact pull request #3
Opened 2023-05-29 18:05 UTC by phihash

1. Huskyとlint-stagedのインストール、package.jsonに設定追記
2. .github/workflowsディレクトリ内にYAMLファイルの記述
をしました!!

2023-05-30 12:58 UTC, yuta-ike requested changes
CIは良さそうです！

huskyの初期設定がうまくいっていないような気がしています...!

うまくいっている場合は、コミット時に以下のようなログが出るので確認してみてください！（Preparing lint-stagedから始まるlint-stagedのログ。huskyがcommitを検知し、lint-staged経由でチェックが走るはず）

<img width="309" alt="image" src="https://github.com/phihash/QuizReact/assets/38308823/c03360d8-d606-4f08-ba0d-96acdc4c4bfa">

2023-05-30 13:00 UTC, yuta-ike commented
この辺、結構古い情報が出回っててカオスな印象だったのですが、やはりpackage.jsonにhuskyの設定を書くのは今は動かないぽいです！（手っ取り早くは公式Docを参照するのが良いかもしれませんが、以下の記事も最新情報を書いてくれてそうです）

[【2023/04最新】husky + lint-staged でコミット前にlintを強制する方法](https://zenn.dev/risu729/articles/latest-husky-lint-staged)

2023-05-31 06:55 UTC, phihash commented
記事ありがとうございます!修正しました。


`
"lint-staged": {
    "*.{js,jsx}": [
      "eslint --fix",
      "prettier --write",
      "git add"
    ]
  }
`
es-lint --fix や git add はつけてもつけなくてもどちらでもよろしいでしょうか

以下コミットログです。

<img width="349" alt="スクリーンショット 2023-05-31 15 42 47" src="https://github.com/phihash/QuizReact/assets/83079502/acc7c994-b9cd-4f3a-8fd1-425b44cd8d07">

2023-05-31 08:36 UTC, yuta-ike approved these changes
[![LGTMeow](https://lgtm-images.lgtmeow.com/2021/11/16/22/3696dde3-3138-49f5-aeb5-ed5c820dc686.webp)](https://lgtmeow.com)

2023-05-31 08:38 UTC, yuta-ike commented
> "lint-staged": { "*.{js,jsx}": [ "eslint --fix", "prettier --write", "git add" ] }
es-lint --fix や git add はつけてもつけなくてもどちらでもよろしいでしょうか

eslint の `--fix`, prettierの `--write` はどちらも、「自動で修正する」オプションです。（この辺は公式Docをご参照ください！）
すなわち、今のコードは、eslint と prettier で自動修正をかけて、その変更を `git add` するという意味になります。（もし自動修正ができないエラーの場合は、コミットが失敗します）

自動修正をしたくない場合は、`--fix` と `--write` を取り除いた上で、`git add` を消します。（変更がないので、`git add` は不要）

自動修正を含めるかどうかは好みによるのかなーと思います！（私は面倒なので修正かけちゃう派です）

2023-05-31 08:39 UTC, yuta-ike approved these changes

2023-05-31 11:11 UTC, phihash commented
ありがとうございます!少々機械的にやってしまいました💦
記事も改めて見直しました。勉強になりました🙇‍♂️

2023-05-31 11:11 UTC, merged